development:
  domain: localhost:3000
  rpx_key: 50994bc3da9a24a24f87c61a6cfcc08ab602eaa2
  rpx_app: CleanSlate
  
test:
  domain: test.host

production:
  domain: cleanslate.heroku.com
  rpx_key: 50994bc3da9a24a24f87c61a6cfcc08ab602eaa2
  rpx_app: CleanSlate
